<a href="https://colab.research.google.com/github/grandff/python-quant/blob/main/2%EA%B0%95_numpy%2C_pandas_%EA%B8%B0%EC%B4%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

numpy 기본 1. 다차원 배열 만들기

In [ ]:
# nupmy 임포트
import numpy as np

# 1차원배열 생성하기
넘파이_배열1 = np.array([1,2,3,4])
넘파이_배열1

array([1, 2, 3, 4])

In [ ]:
# 2차원배열 생성하기
넘파이_배열2 = np.array([[1,2,3,4],[11,12,13,14]])
넘파이_배열2

array([[ 1,  2,  3,  4],
       [11, 12, 13, 14]])

In [ ]:
넘파이_배열3 = np.array([
                    [
                     [1,2,3,4], [11,12,13,14]
                    ],
                    [
                     [21,22,23,24],[31,32,33,34]
                    ]
])
넘파이_배열3

array([[[ 1,  2,  3,  4],
        [11, 12, 13, 14]],

       [[21, 22, 23, 24],
        [31, 32, 33, 34]]])

In [ ]:
# 배열의 모양 보기 (shape 이용)
print(넘파이_배열1.shape)
print(넘파이_배열2.shape)
print(넘파이_배열3.shape)

(4,)
(2, 4)
(2, 2, 4)


In [ ]:
# 임의로 배열 초기화 하기
z1 = np.zeros([4])  # 0으로 채운 배열 만들기
o2 = np.ones([3,4]) # 1로 채운 배열 만들기
r2 = np.random.randn(2,3) # 랜덤한 숫자 배열 만들기

In [ ]:
z1, o2, r2

(array([0., 0., 0., 0.]), array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]), array([[-1.00942576,  0.76678742,  0.5494052 ],
        [ 0.25499553,  0.53326151, -0.6424472 ]]))

In [ ]:
# 무척 큰 4차원 배열 생성
r4 = np.random.randn(2,2,4,5).round(3)
r4

array([[[[ 0.566,  0.887,  0.1  ,  0.022, -1.499],
         [-0.621, -0.301, -1.197, -0.3  ,  0.512],
         [-0.259,  0.966,  0.977,  2.45 , -0.437],
         [-0.898,  0.111,  0.588, -0.925, -1.214]],

        [[ 0.95 , -0.152, -0.193,  0.34 , -0.448],
         [ 0.345,  1.116,  1.319, -1.998, -0.77 ],
         [-0.366, -0.918, -1.41 , -0.386, -0.275],
         [ 1.269, -1.375,  0.11 ,  1.611,  1.52 ]]],


       [[[ 0.914, -0.424, -0.802, -2.253, -0.688],
         [-1.472, -0.493, -0.102, -0.289,  0.773],
         [-0.093,  1.105,  0.121,  0.672, -0.446],
         [ 0.141, -0.623, -1.018, -0.628, -0.132]],

        [[-0.82 , -2.702,  0.715, -1.152, -3.534],
         [ 0.305,  1.128,  0.942,  0.817,  1.365],
         [-0.821,  0.258, -1.22 ,  0.146,  0.834],
         [ 0.582,  0.196, -0.011,  1.717,  0.208]]]])

numpy 기본 2. Indexing과 Slicing

In [ ]:
# r4 배열에서 [두번째][첫번째] 접근해서 가져오기
r4[1][1]

array([[-0.82 , -2.702,  0.715, -1.152, -3.534],
       [ 0.305,  1.128,  0.942,  0.817,  1.365],
       [-0.821,  0.258, -1.22 ,  0.146,  0.834],
       [ 0.582,  0.196, -0.011,  1.717,  0.208]])

In [ ]:
r4[1][1][0]

array([-0.82 , -2.702,  0.715, -1.152, -3.534])

In [ ]:
r4[1][1][0][3]

-1.152

In [ ]:
r4[1, 1, 0, 3] # 대괄호 대신 쉼표 , 도 차원 접근에 가능함

-1.152

In [ ]:
# Indexing 과 Slicing 같이 적용하기
r4[1][1][0:3:2]

array([[-0.82 , -2.702,  0.715, -1.152, -3.534],
       [-0.821,  0.258, -1.22 ,  0.146,  0.834]])

Broadcasting

In [ ]:
arr = np.array([[1,2,3,4],[10,11,12,13]])
arr

array([[ 1,  2,  3,  4],
       [10, 11, 12, 13]])

In [ ]:
arr + arr # 배열끼리 연산하기(+-*/ 모두 가능)

array([[ 2,  4,  6,  8],
       [20, 22, 24, 26]])

In [ ]:
arr + 20    # 덧셈 브로드캐스팅

array([[21, 22, 23, 24],
       [30, 31, 32, 33]])

In [ ]:
arr * 100   # 곱셈 브로드캐스팅

array([[ 100,  200,  300,  400],
       [1000, 1100, 1200, 1300]])

In [ ]:
# 배열 전체의 덧셈, 평균, 곱셈, 최댓값, 최솟값
arr.sum()   # 덧셈
arr.mean()  # 평균
arr.prod()  # 곱셈
arr.max()   # 최댓값
arr.min()   # 최솟값

1

In [ ]:
# 배열에서 최대인 원소의 번호, 최소인 원소의 번호
arr.argmax(), arr[1].argmax(),  arr.argmin()

(7, 3, 0)

nupmy 기본 4. 고급 Broadcasting

In [ ]:
arr1 = np.array([[0,0,0],[10,10,10],[20,20,20],[30,30,30]])
arr2 = np.array([[0,1,2],[0,1,2],[0,1,2],[0,1,2]])
arr1.shape, arr2.shape

((4, 3), (4, 3))

In [ ]:
arr1 + arr2

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [ ]:
arr1 + np.array([0,1,2])  # 4x3 + 1x3

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

pandas 기본 1. serires 행 x 값 데이터

In [ ]:
# 예제 주식 데이터 파일 다운로드
!wget "https://gist.githubusercontent.com/solaris33/e9938d2f36969a28b5cf15dfc17a77b3/raw/402e4494a6a0cce7d1d1d543cb5d9ac7831c6d1b/stock.adj_close.csv" -O "stock.adj_close.csv"

--2021-10-03 02:27:10--  https://gist.githubusercontent.com/solaris33/e9938d2f36969a28b5cf15dfc17a77b3/raw/402e4494a6a0cce7d1d1d543cb5d9ac7831c6d1b/stock.adj_close.csv
Resolving gist.githubusercontent.com (gist.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to gist.githubusercontent.com (gist.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9051250 (8.6M) [text/plain]
Saving to: ‘stock.adj_close.csv’

stock.adj_close.csv 100%[===================>]   8.63M  --.-KB/s    in 0.04s   

2021-10-03 02:27:10 (206 MB/s) - ‘stock.adj_close.csv’ saved [9051250/9051250]



In [ ]:
# pandas 임포트
import pandas as pd

In [ ]:
# 주가 데이터를 불러오고, series 하나를 고름
주가_데이터 = pd.read_csv('stock.adj_close.csv', index_col=0)   # read_csv 사용해서 csv파일 read
my_series = 주가_데이터.loc['A005930']['2020-09-09':]     # loc를 통해 특정 컬럼 접근, 인덱싱 사용해서 일부만 사용

In [ ]:
my_series

2020-09-09    58400.0
2020-09-10    59200.0
2020-09-11    59000.0
2020-09-14    60400.0
2020-09-15    61000.0
2020-09-16    61000.0
2020-09-17    59500.0
2020-09-18    59300.0
Name: A005930, dtype: float64

In [ ]:
my_series.index   # Series의 인덱스 보기

Index(['2020-09-09', '2020-09-10', '2020-09-11', '2020-09-14', '2020-09-15',
       '2020-09-16', '2020-09-17', '2020-09-18'],
      dtype='object')

In [ ]:
my_series.name    # Series의 이름 보기

'A005930'

In [ ]:
type(my_series) # 타입 확인하기

pandas.core.series.Series

pandas 기본 2. 접근, 연산, 생성

In [ ]:
my_series.loc['2020-09-15'] # 인덱스로 접근

61000.0

In [ ]:
my_series.iloc[4]   # 배열 번호로 접근

61000.0

In [ ]:
my_series.loc['2020-09-15' : '2020-09-17']    # 인덱스로 Slicing

2020-09-15    61000.0
2020-09-16    61000.0
2020-09-17    59500.0
Name: A005930, dtype: float64

In [ ]:
my_series.iloc[4:7]   # 배열 번호로 Slicing (끝 포함 X)

2020-09-15    61000.0
2020-09-16    61000.0
2020-09-17    59500.0
Name: A005930, dtype: float64

In [ ]:
my_series.iloc[4:] + my_series.iloc[4:]

2020-09-15    122000.0
2020-09-16    122000.0
2020-09-17    119000.0
2020-09-18    118600.0
Name: A005930, dtype: float64

In [ ]:
my_series.loc['2020-09-15' :: 3] + 30000    # Scalar Broadcasting

2020-09-15    91000.0
2020-09-18    89300.0
Name: A005930, dtype: float64

In [ ]:
my_series.iloc[4:].mean()   # 평균

60200.0

pandans 기본 3. DataFrame 행x열 데이터

In [ ]:
# 불러온 주가 데이터에서 불러오고, dataframe 하나를 추출
my_df = 주가_데이터.T.loc['2020-09-09':, 'A005900' : 'A006000']

In [ ]:
my_df

Symbol      A005930  A005940  A005950  A005960  A005980  A005990
2020-09-09  58400.0   9190.0   9080.0  11000.0    671.0   7990.0
2020-09-10  59200.0   9280.0   9280.0  11150.0    671.0   7960.0
2020-09-11  59000.0   9270.0   9360.0  11050.0    671.0   8120.0
2020-09-14  60400.0   9370.0   9400.0  11200.0    671.0   8200.0
2020-09-15  61000.0   9470.0   9390.0  11350.0    671.0   8180.0
2020-09-16  61000.0   9530.0   9080.0  11250.0    671.0   8180.0
2020-09-17  59500.0   9320.0   8880.0  11000.0    671.0   8000.0
2020-09-18  59300.0   9320.0   9070.0  10850.0    671.0   8020.0

pandas 기본 4. DataFrame 접근

In [ ]:
my_df.loc['2020-09-15', 'A005930']  # loc 단일 원소 접근

61000.0

In [ ]:
# .loc [ 인덱스, 컬럼 slice ] 로 접근 -> Series 변환
my_df.loc['2020-09-15', 'A005930' : 'A005950']

Symbol
A005930    61000.0
A005940     9470.0
A005950     9390.0
Name: 2020-09-15, dtype: float64